[main]
launch-prefix=env DISPLAY=:0
#icon-theme=Adwaita
icons-enabled=yes
match-mode=fuzzy
fields=name,comment,filename,categories,keywords,generic
terminal=footclient -e
line-height=20
width=16
lines=8
horizontal-pad=0
vertical-pad=4
inner-pad=2
anchor=center
image-size-ratio=0.9
font=Noto Sans:size=15

[colors]
background=000000ff
text=ffffffff
prompt=ffffffff
input=ffffffff
match=ffffffff
selection=222222ff
selection-text=ffffffff
selection-match=ffffffff
border=555555ff

[border]
width=0
radius=0

